model:
  model: ./config/model.yaml
  pretrain_model: yolo11n-obb.pt

dataset:
  data: ./config/dataset.yaml

hyperparameter:
  epochs: 250
  # fliplr: 0
  ## flipud: 0.25
  ## scale: 0
  ## mosaic: 0
  # imgsz: 1280
  ## multi_scale: True
  # 其他超参数根据实验进行配置
